### ISSUE TITLE
Estimating winner probability

### ISSUE THREAD

**Issue by Ape** [sublee/trueskill#18]
Currently trueskill has a way to estimate the draw probability for a given match with `quality()` function, but I would like to have a function for estimating the winner with a set of players. Is this possible to do?

For example, let's say I have three players with some ratings and they will play a three-player free-for-all. The program would give the probability of winning for each player:

```
Player 1: 68%
Player 2: 25%
Player 3:  7%
```

**Comment by Tjorriemorrie** [comment]
Refer https://github.com/sublee/trueskill/pull/17

![rejected](https://user-images.githubusercontent.com/1099093/31860984-7fc204d6-b76f-11e7-9a2d-126654a98b5c.jpg)

**Comment by sublee** [comment]
No, I will not accept a win probability function in this library.  It is the most common issue but not a part of the TrueSkill™ paper. 

Anyway, you can calculate a win probability by yourself.  Check #1.

**Comment by lukebyrne** [comment]
@Ape Did you ever come up with a function for your question?
