### ISSUE TITLE
Draw probability usage

### ISSUE THREAD

**Issue by Samcfuchs** [sublee/trueskill#38]
I've noticed that draw probability given in the environment doesn't seem to effect the output of `quality`, even though the documentation states that `quality` should give the draw probability. Does the given draw probability have any effect on the results of the model, and in what way? Is there a way to get a more accurate number? The output of `quality` seems greatly inflated.

**Comment by sublee** [comment]
I think you should ask Microsoft Research who invented the algorithm. If I implemented it wrong, please report here.
